spring:
  application:
    name: accounts

  config:
    import: ${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071}

eureka:
  instance:
    ip-address: true
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 8
    eureka-connection-idle-timeout-seconds: 30
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    shutdown:
      enabled: true

    env:
      enabled: true


info:
  app:
    name: "account-service"
    description: "Micro-lab Account-Service Application"
    version: "1.0.0"



