server:
  port: 8761

spring:
  application:
    name: eureka-server

  config:
    import: optional:${SPRING_CONFIG_IMPORT:configserver:http://localhost:8071}

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
info:
  version : 1.0.0
