server:
  port: 8071

spring:
  application:
    name: config-server

  profiles:
    active: git
  #active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Suresh322/micro-services-lab.git
          default-label: master
          search-paths:
            - config-server/src/main/resources/config
          timeout: 5
          clone-on-start: true
          force-pull: true
          #native:
          #search-locations:
          #-classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh
